-- MySQL Script generated by MySQL Workbench
-- 07/03/17 08:17:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestor_patrimonio_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestor_patrimonio_db` ;

-- -----------------------------------------------------
-- Schema gestor_patrimonio_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestor_patrimonio_db` DEFAULT CHARACTER SET utf8 ;
USE `gestor_patrimonio_db` ;

-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `apelido` VARCHAR(45) NULL,
  `login` VARCHAR(145) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`patrimonio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`patrimonio` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`patrimonio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(12,2) NULL,
  `total_ativos` DECIMAL(12,2) NULL,
  `total_passivos` DECIMAL(12,2) NULL,
  `patrimonio_liquido` DECIMAL(12,2) NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_patrimonio_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_patrimonio_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestor_patrimonio_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`ativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`ativo` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`ativo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` LONGTEXT NULL,
  `valor_estimado` DECIMAL(12,2) NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_ativo_patrimonio1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_ativo_patrimonio1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestor_patrimonio_db`.`patrimonio` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`option` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`option` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chave` VARCHAR(45) NULL,
  `valor` VARCHAR(145) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`documento` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(145) NULL,
  `conteudo` LONGTEXT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_documento_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_documento_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestor_patrimonio_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`meta_financeira`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`meta_financeira` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`meta_financeira` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(145) NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `data_inicio` DATE NULL,
  `data_final` DATE NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `status` VARCHAR(45) NULL,
  `descricao` LONGTEXT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_meta_financeira_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_meta_financeira_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestor_patrimonio_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`passivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`passivo` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`passivo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` LONGTEXT NULL,
  `valor_estimado` DECIMAL(12,2) NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_passivo_patrimonio1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_passivo_patrimonio1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestor_patrimonio_db`.`patrimonio` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`fluxo_de_caixa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`fluxo_de_caixa` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`fluxo_de_caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NOT NULL,
  `mes` INT NULL,
  `status` VARCHAR(45) NULL,
  `desempenho` VARCHAR(45) NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `total` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `total`),
  INDEX `fk_fluxo_de_caixa_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_fluxo_de_caixa_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gestor_patrimonio_db`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`receita` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`receita` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` LONGTEXT NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `fluxo_de_caixa_id` INT NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id`, `fluxo_de_caixa_id`, `usuario_id`),
  INDEX `fk_receita_fluxo_de_caixa1_idx` (`fluxo_de_caixa_id` ASC, `usuario_id` ASC),
  CONSTRAINT `fk_receita_fluxo_de_caixa1`
    FOREIGN KEY (`fluxo_de_caixa_id`)
    REFERENCES `gestor_patrimonio_db`.`fluxo_de_caixa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`despesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`despesa` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`despesa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` LONGTEXT NULL,
  `valor_estimado` DECIMAL(12,2) NOT NULL,
  `fluxo_de_caixa_id` INT NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id`, `fluxo_de_caixa_id`, `usuario_id`, `status`),
  INDEX `fk_despesa_fluxo_de_caixa1_idx` (`fluxo_de_caixa_id` ASC, `usuario_id` ASC),
  CONSTRAINT `fk_despesa_fluxo_de_caixa1`
    FOREIGN KEY (`fluxo_de_caixa_id`)
    REFERENCES `gestor_patrimonio_db`.`fluxo_de_caixa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_patrimonio_db`.`medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestor_patrimonio_db`.`medida` ;

CREATE TABLE IF NOT EXISTS `gestor_patrimonio_db`.`medida` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` LONGTEXT NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `data` DATE NULL,
  `meta_financeira_id` INT NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `meta_financeira_id`, `usuario_id`),
  INDEX `fk_medida_meta_financeira1_idx` (`meta_financeira_id` ASC, `usuario_id` ASC),
  CONSTRAINT `fk_medida_meta_financeira1`
    FOREIGN KEY (`meta_financeira_id` , `usuario_id`)
    REFERENCES `gestor_patrimonio_db`.`meta_financeira` (`id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
